#!/bin/sh

find /opt/hashstack/programs/cudaHashcat -name \*.outfiles -print0 | xargs -0 rm -rf 2>/dev/null
find /opt/hashstack/programs/cudaHashcat -name \*.induct -print0 | xargs -0 rm -rf 2>/dev/null
find /opt/hashstack/programs/cudaHashcat -name \*.log -print0 | xargs -0 rm -rf 2>/dev/null

rm -fr /opt/hashstack/programs/cudaHashcat/kernels
rm -f  /opt/hashstack/programs/cudaHashcat/eula.accepted
rm -f  /opt/hashstack/programs/cudaHashcat/cudaHashcat64.bin

exit 0
